Refactor and introduce new flag with the script additions

diff --git a/jpf-sv-comp b/jpf-sv-comp
--- a/jpf-sv-comp
+++ b/jpf-sv-comp
@@ -29,6 +29,22 @@ if [ ! -s "${BM[0]}" ] || [ ! -s "$PROP_FILE" ] ; then
   exit 1
 fi
 
+echo "PROP_FILE=$PROP_FILE"
+  ASSERTION_MODE="FALSE"
+  RUNTIME_EXCEPTION_MODE="FALSE"
+  grep "assert" $PROP_FILE
+  if [ $? -eq 0 ]; then
+    ASSERTION_MODE="TRUE"
+  fi
+
+  grep "Exception" $PROP_FILE
+  if [ $? -eq 0 ]; then
+    RUNTIME_EXCEPTION_MODE="TRUE"
+  fi
+
+echo "ASSERTION_MODE=$ASSERTION_MODE"
+echo "RUNTIME_EXCEPTION_MODE=$RUNTIME_EXCEPTION_MODE"
+
 LOG=`mktemp -t jpf-log.XXXXXX`
 DIR=`mktemp -d -t jpf-benchmark.XXXXXX`
 
@@ -45,9 +61,15 @@ echo "symbolic.dp=z3bitvector" >> $DIR/config.jpf
 echo "symbolic.bvlength=64" >> $DIR/config.jpf
 echo "search.depth_limit=13" >> $DIR/config.jpf
 echo "symbolic.strings=true" >> $DIR/config.jpf
+echo "symbolic.string_dp=z3str3" >> $DIR/config.jpf
 echo "symbolic.string_dp_timeout_ms=3000" >> $DIR/config.jpf
 echo "symbolic.lazy=on" >> $DIR/config.jpf
 echo "symbolic.arrays=true" >> $DIR/config.jpf
+if [ $RUNTIME_EXCEPTION_MODE = "TRUE" ] ; then
+  echo "runtime.exception=true" >>
+  echo "search.multiple_errors = true" >> $DIR/config.jpf
+fi
+echo "nullPointer.exception=false" >> $DIR/config.jpf
 echo $DIR/config.jpf
 
 # run SPF
@@ -63,10 +85,24 @@ grep "no errors detected" $LOG > /dev/null
 if [ $? -eq 0 ]; then
   echo "SAFE"
 else
-  grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
-  if [ $? -eq 0 ]; then
-    echo "UNSAFE"
+  if [ $ASSERTION_MODE = "TRUE" ]; then
+    echo "inside assertion_mode=true"
+    grep "^error.*NoUncaughtExceptionsProperty.*AssertionError" $LOG > /dev/null
+    if [ $? -eq 0 ]; then
+      echo "UNSAFE"
+    else
+      echo "UNKNOWN"
+    fi
+  elif [ $RUNTIME_EXCEPTION_MODE = "TRUE" ]; then
+    echo "inside runtime_exception_mode=true"
+    grep "java.lang.*Exception" $LOG > /dev/null
+    if [ $? -eq 0 ]; then
+      echo "UNSAFE"
+    else
+      echo "UNKNOWN"
+    fi
   else
-    echo "UNKNOWN"
+    echo unsupported case. Failing
+    exit 1;
   fi
 fi
